name: Code style

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    name: Code Style
    steps:
    - uses: actions/checkout@v2
    - uses: psf/black@stable
