name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  doc-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version:
          - '3.9'
          - '3.10'

    name: Python ${{ matrix.python_version }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}
        architecture: x64

    - name: Prepare environment
      run: |
        python3 -m pip install --upgrade pip poetry

    - name: Install dependencies
      env:
        PIP_PREFER_BINARY: 1
      run: |
        python3 -m poetry install

    - name: Run doc tests
      run: |
        python3 tests.py
